config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :conversions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversion.rb
# frozen_string_literal: true

class Conversion < ApplicationRecord
  AVAILABLE_CURRENCIES = %w[AUD BGN BRL CAD CHF CNY CZK DKK EUR GBP HKD HRK HUF IDR ILS INR
                            JPY KRW MXN MYR NOK NZD PHP PLN RON RUB SEK SGD THB TRY USD ZAR].freeze
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/conversions_controller.rb
# frozen_string_literal: true

require 'net/http'
class ConversionsController < ApplicationController
  before_action :set_conversion, only: %i[show edit update destroy]

  # GET /conversions
  # GET /conversions.json
  def index
    @conversion = Conversion.new
    @conversions = Conversion.all
  end

  # GET /conversions/1
  # GET /conversions/1.json
  def show
    @array_datewise = fetch_data
    uri = URI("http://data.fixer.io/api/latest?access_key=90b760542e55ffc6a374fa98ca6f76a0&symbols=#{@conversion.target_currency}")
    res = JSON.parse(Net::HTTP.get(uri))
    @current_rate = res['rates'][@conversion.target_currency.to_s]
  end

  # GET /conversions/new
  def new
    @conversion = Conversion.new
  end

  # GET /conversions/1/edit
  def edit; end

  # POST /conversions
  # POST /conversions.json
  def create
    @conversion = Conversion.new(conversion_params)

    respond_to do |format|
      if @conversion.save
        format.html { redirect_to @conversion, notice: 'Conversion was successfully created.' }
        format.json { render :show, status: :created, location: @conversion }
      else
        format.html { render :new }
        format.json { render json: @conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversions/1
  # PATCH/PUT /conversions/1.json
  def update
    respond_to do |format|
      if @conversion.update(conversion_params)
        format.html { redirect_to @conversion, notice: 'Conversion was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversion }
      else
        format.html { render :edit }
        format.json { render json: @conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversions/1
  # DELETE /conversions/1.json
  def destroy
    @conversion.destroy
    respond_to do |format|
      format.html { redirect_to conversions_url, notice: 'Conversion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def fetch_data
    hash = {}
    @conversion.week_count.times do |n|
      date = (Date.today - (n + 1).weeks).strftime('%Y-%m-%d')
      uri = URI("http://data.fixer.io/api/#{date}?access_key=90b760542e55ffc6a374fa98ca6f76a0&symbols=#{@conversion.target_currency}")
      res = JSON.parse(Net::HTTP.get(uri))
      hash[date.to_s] = res['rates'][@conversion.target_currency.to_s]
    end
    hash
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_conversion
    @conversion = Conversion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def conversion_params
    params.require(:conversion).permit(:base_currency, :target_currency, :base_amount, :week_count)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/conversions_helper.rb
# frozen_string_literal: true

module ConversionsHelper
end

app/views/conversions/_conversion.html.haml
%tr{id: "#{conversion.id}", 'data-link':"#{edit_conversion_path(conversion.id)}"}
  %td
    = conversion.id
  %td
    = conversion.base_currency
  %td
    = conversion.base_amount
  %td
    = link_to conversion_path(conversion.id) do
      %i.fa.fa-folder-open.text-info.mr-2{"aria-hidden" => "true", "data-toggle"=>"tooltip", "title"=>"View Details"}
    = link_to task_conversion_path(conversion.id) do
      %i.fa.fa-pencil.text-secondary{"aria-hidden" => "true", "data-toggle"=>"tooltip", "title"=>"Edit"}
    %a
      %i.fa.fa-folder.text-danger.ml-2{"aria-hidden" => "true", "data-toggle"=>"tooltip", "title"=>"Preview conversion"}

    = link_to conversion_path(conversion), method: :delete do
      %i.fa.fa-trash.text-danger.ml-2{"aria-hidden" => "true", "data-toggle"=>"tooltip", "title"=>"Delete", "name" => "#{conversion.id}", "class" => "delete-conversion", "id" => "T#{conversion.id}"}

app/views/conversions/_form.html.haml
= form_with(model: @conversion, remote: true) do |form|
  - if @conversion.errors.any?
    #error_explanation
      %h2
        = pluralize(@conversion.errors.count, "error")
        prohibited this @conversion from being saved:
      %ul
        - @conversion.errors.full_messages.each do |message|
          %li= message
  .row.mr-3.ml-3
    .field.col-3
      = form.select(:base_currency, ["EUR"], { prompt: "Select Base Currency" }, { :class => 'form-control select2', style: 'width: 100%;' ,required: true})
    .field.col-3
      = form.number_field :base_amount, placeholder: "Enter Amount", class: "form-control",required: true
    .field.col-3
      = form.select(:target_currency, Conversion::AVAILABLE_CURRENCIES, { prompt: "Select Target Currency" }, { :class => 'form-control select2', style: 'width: 100%;', required: true })
    .field.col-3
      = form.select(:week_count, 1..25, { prompt: "Select no.of weeks" }, { :class => 'form-control select2', style: 'width: 100%;', required: true})
    
    = form.submit 'Convert', class: "mt-5 btn btn-primary"

app/views/conversions/create.js.erb
$("#conversionTable").prepend("<%= j render 'conversions/conversion', conversion: @conversion %>")

app/views/conversions/edit.html.haml
%h1 Editing Conversion
= render 'form', conversion: @conversion
= link_to 'Show', @conversion
|
= link_to 'Back', conversions_path

app/views/conversions/index.html.haml
%p#notice= notice
%h1 Conversions

= render 'form'
%hr
  .card-body.table-responsive
    %table.table.table-hover.table-valign-middle
      %thead
        %tr
          %th Base currency
          %th Target currency
          %th Base amount
          %th Number Of Weeks
          %th{:colspan => "3"}
      %tbody#conversionTable
        - @conversions.each do |conversion|
          %tr
            %td= conversion.base_currency
            %td= conversion.target_currency
            %td= conversion.base_amount
            %td= conversion.week_count
            %td= link_to 'Show', conversion
            %td= link_to 'Edit', edit_conversion_path(conversion)
            %td= link_to 'Destroy', conversion, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Conversion', new_conversion_path

app/views/conversions/new.html.haml
%h1 New Conversion
= render 'form', conversion: @conversion
= link_to 'Back', conversions_path

app/views/conversions/show.html.haml
%p#notice= notice
%p
  %strong Base currency:
  = @conversion.base_currency
%p
  %strong Target currency:
  = @conversion.target_currency
%p
  %strong Base amount:
  = @conversion.base_amount
%p
  %strong Current Target Rate:
  = @current_rate
%p
  %strong Target amount Now:
  = @conversion.base_amount*@current_rate
.row
  .col-4
    = line_chart @array_datewise,xtitle: "Week", ytitle: "Rate"
  .col-8
    .card-body.table-responsive
      %table.table.table-hover.table-valign-middle
        %thead
          %tr
            %th Year-Week
            %th Target currency Rate
            %th Base amount
            %th Target Amount
            %th Profit/Loss
        %tbody#conversionTable
          - @array_datewise.each do |key, value|
            %tr
              %td= key.to_date.strftime("%Y-Week no-%U")
              %td.rate
                = value
              %td= @conversion.base_amount
              %td= @conversion.base_amount*value
              %td= @current_rate > value ? "Profit" : "Loss"


= link_to 'Edit', edit_conversion_path(@conversion)
|
= link_to 'Back', conversions_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ForexRateConverter
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container.container-fluid
      = yield